name: Android CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: set up JDK 9
      uses: actions/setup-java@v3
      with:
        java-version: '9'
        distribution: 'adopt-openj9'
        cache: gradle
    - name: Grant execute permission for gradlew
      run: |
            chmod +x gradlew
            git update-index --chmod=+x gradle
    - name: Build with Gradle
      run: sudo gradlew build
